# Configuration file for running the mnist_fc benchmark (large models).
general:
  complete_verifier: bab-refine
model:
  input_shape: [-1, 1, 28, 28]  # This onnx model has input shape [-1, 784] which is not compatible with our MIP solution
solver:
  batch_size: 4096
  beta-crown:
    iteration: 20
    lr_beta: 0.03
    enable_opt_interm_bounds: True
  mip:
    parallel_solvers: 8
    solver_threads: 1
    refine_neuron_time_percentage: 0.8
  start_save_best: -1
bab:
  branching:
    candidates: 5
    reduceop: max
attack:
  attack_mode: diversed_PGD
  pgd_restarts: 100
