# Configuration file for running the mnist_fc benchmark (small model).
general:
  complete_verifier: mip
model:
  input_shape: [-1, 1, 28, 28]  # This onnx model has input shape [-1, 784] which is not compatible with our MIP solution
solver:
  batch_size: 500
  beta-crown:
    iteration: 20
    lr_beta: 0.03
  mip:
    parallel_solvers: 1
    solver_threads: 1
    refine_neuron_time_percentage: 0.8
bab:
  branching:
    candidates: 5
    reduceop: max
