site_name: Auto-Verify Docs

theme:
  name: "material"

plugins: 
  - mkdocstrings

nav:
  - Auto-Verify Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md