name: __av__abcrown

channels:
  - pytorch
  - conda-forge
  - gurobi
  - nodefaults  # Explicitly block Anaconda repos

dependencies:
  # Critical pinned packages
  - python=3.9
  - numpy=1.21.5
  - pandas=1.3.4
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - tensorboard
  - tensorboard-data-server
  - tensorboard-plugin-wit
  - tensorflow
  - tensorflow-base
  - tensorflow-estimator
  - gurobi=9.5.1

  # Unpinned packages (let Conda resolve versions)
  - absl-py
  - aiohttp
  - aiosignal
  - appdirs
  - astor
  - astunparse
  - async-timeout
  - asynctest
  - attrs
  - blas
  - blinker
  - blosc
  - bottleneck
  - brotli
  - brotlipy
  - brunsli
  - bzip2
  - c-ares
  - ca-certificates
  - cachetools
  - certifi
  - cffi
  - cfitsio
  - charls
  - charset-normalizer
  - click
  - cloudpickle
  - cryptography
  - cycler
  - cytoolz
  - dask-core
  - dataclasses
  - dbus
  - expat
  - ffmpeg
  - fontconfig
  - fonttools
  - freetype
  - frozenlist
  - fsspec
  - gast
  - giflib
  - graphviz
  - glib
  - gmp
  - gnutls
  - google-auth
  - google-auth-oauthlib
  - google-pasta
  - grpcio
  - gst-plugins-base
  - gstreamer
  - h5py
  - hdf5
  - icu
  - idna
  - imagecodecs
  - imageio
  - importlib-metadata
  - jpeg
  - jxrlib
  - keras
  - keras-preprocessing
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libaec
  - libclang
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran4
  - libgomp
  - libiconv
  - libidn2
  - libllvm10
  - libnghttp2
  - libpng
  - libprotobuf
  - libssh2
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libunistring
  - libuuid
  - libuv
  - libwebp
  - libwebp-base
  - libxcb
  - libxml2
  - libzopfli
  - locket
  - lz4-c
  - markdown
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - multidict
  - munkres
  - ncurses
  - nettle
  - networkx
  - numexpr
  - oauthlib
  - openh264
  - openjpeg
  - openssl
  - opt_einsum
  - packaging
  - pandas
  - partd
  - pcre
  - pillow
  - pip
  - psutil
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pyjwt
  - pyopenssl
  - pyparsing
  - pysocks
  - python-dateutil
  - python-flatbuffers
  - pytorch-mutex
  - pytz
  - pywavelets
  - pyyaml
  - qt
  - readline
  - requests
  - requests-oauthlib
  - rsa
  - scikit-image
  - scipy
  - setuptools
  - sip
  - six
  - snappy
  - sortedcontainers
  - sqlite
  - termcolor
  - tifffile
  - tk
  - toolz
  - torchaudio
  - torchvision
  - tornado
  - tqdm
  - typing-extensions
  - typing_extensions
  - urllib3
  - werkzeug
  - wheel
  - wrapt
  - xz
  - yaml
  - yarl
  - zfp
  - zipp
  - zlib
  - zstd
  
  # Pip dependencies
  - pip:
      - flatbuffers==2.0
      - onnx==1.11.0
      - git+https://github.com/KaidiXu/onnx2pytorch@102cf22e64ea7fae9462c1ba0feaa250ac0bc628#egg=onnx2pytorch
      - onnxruntime==1.11.0
      - onnxoptimizer==0.3.13 
      - skl2onnx==1.11.1
      - protobuf==3.20.1
      - intel-openmp
      - graphviz
