name: __av__mnbab

channels:
  - pytorch
  - conda-forge  
  - gurobi
  - nodefaults  # Explicitly block Anaconda repos

dependencies:
  # Critical pinned packages
  - python=3.9
  - gurobi=9.1.2

  # Other conda packages (let conda resolve versions)
  - cddlib
  - gmp
  - m4
  - mpfr
  - _libgcc_mutex
  - _openmp_mutex
  - ca-certificates
  - certifi
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libstdcxx-ng
  - ncurses
  - openssl
  - pip
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib

  # Pip dependencies (unchanged)
  - pip:
    - absl-py==1.4.0
    - appdirs==1.4.4
    - astunparse==1.6.3
    - attrs==23.1.0
    - black==23.3.0
    - bunch==1.0.1
    - cachetools==5.3.0
    - cfgv==3.3.1
    - chardet==5.1.0
    - charset-normalizer==3.1.0
    - click==8.1.3
    - comet-ml==3.32.6
    - configobj==5.0.6
    - coverage==7.2.5
    - cycler==0.11.0
    - dill==0.3.6
    - distlib==0.3.6
    - dulwich==0.21.5
    - everett==3.1.0
    - exceptiongroup==1.1.1
    - filelock==3.12.0
    - flatbuffers==1.12
    - fonttools==4.38.0
    - gast==0.4.0
    - google-auth==2.18.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.54.2
    - gurobipy==9.1.2
    - h5py==3.8.0
    - identify==2.5.24
    - idna==3.4
    - importlib-metadata==6.6.0
    - iniconfig==1.1.1
    - jsonschema==3.2.0
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - libclang==16.0.0
    - markdown==3.4.3
    - markupsafe==2.1.2
    - matplotlib==3.5.3
    - mxnet==1.9.1
    - mypy-extensions==0.4.3
    - nodeenv==1.8.0
    - numpy==1.21.0
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.2.2
    - onnx==1.11.0
    - onnxruntime==1.11.0
    - opt-einsum==3.3.0
    - packaging==23.1
    - pandas==1.2.5
    - pathspec==0.11.1
    - pillow==9.1.1
    - platformdirs==2.6.1
    - pluggy==1.0.0
    - pre-commit==2.20.0
    - protobuf==3.19.6
    - py==1.10.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pyparsing==2.4.7
    - pyrsistent==0.19.3
    - pytest==7.3.1
    - pytest-cov==4.0.0
    - python-box==6.1.0
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pyyaml==5.4.1
    - regex==2023.5.5
    - requests==2.30.0
    - requests-oauthlib==1.3.1
    - requests-toolbelt==1.0.0
    - rsa==4.9
    - semantic-version==2.10.0
    - sentry-sdk==1.23.0
    - simplejson==3.19.1
    - six==1.16.0
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.32.0
    - termcolor==2.3.0
    - toml==0.10.2
    - tomli==2.0.1
    - torch==1.11.0
    - torchvision==0.12.0
    - tqdm==4.65.0
    - typed-ast==1.4.3
    - typing-extensions==3.10.0.0
    - urllib3==1.26.15
    - virtualenv==20.4.7
    - websocket-client==1.3.3
    - werkzeug==2.2.3
    - wrapt==1.15.0
    - wurlitzer==3.0.3
    - zipp==3.4.1
